version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5434:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      
  redis:
    image: redis:latest
    # container_name: redis-server
    ports:
      - "6379:6379"  # Expose Redis on localhost port 6379
    # environment:
      # REDIS_PASSWORD: Beaverasdf1234  # Set Redis password
    command: ["redis-server", "--databases", "2"]
    volumes:
      - redis-data:/data  # Persist Redis data
    restart: unless-stopped
    
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION:-latest}
    # container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
  
  # backend:
  #   build: .
  #   ports:
  #     - "8002:8002"
  #   depends_on:
  #     - db
  #     - redis
  #     - nacos
  #   networks:
  #     - app-network
  #   restart: always


volumes:
  redis-data:
    driver: local